### ISSUE TITLE
Replace Apache with a simple Python WebServer

### ISSUE THREAD

**Issue by derogab** [derogab/coingraph#2]
A developer on [hacker-news](https://news.ycombinator.com/item?id=15156021) made me notice that coingraph uses too many dependencies that can be replaced with home-made alternatives.

One of these is the web server.
Now I use Apache, but it would be nice to replace it with a python web server.

**Comment by gmemstr** [comment]
Currently working on looking into this - looks like PHP also has a built in webserver which could help.

**Comment by derogab** [comment]
Cool. I have never used Tornado, but I will definitely read the documentation.

So are you working to replace Apache with Tornado?

**Comment by gmemstr** [comment]
@derogab Yup - replacing all the PHP so it should be all independent.

**Comment by derogab** [comment]
Wow. I look forward to your commit.

**Comment by gmemstr** [comment]
Ported most of the functionality of the PHP file to Python but it doesn't seem to get the right value from the database (`price` returns as `usd` for some reason). Looking into it but will hopefully have the PR open by tomorrow night. Also will make some tweaks to main.js if needed to parse results (should they differ from PHP results).

**Comment by gmemstr** [comment]
#3 fixes this issue.
