### ISSUE TITLE
polling-xhr.js error

### ISSUE THREAD

**Issue by tovi34** [derogab/coingraph#45]
polling-xhr.js:268 GET http://localhost:8081/socket.io/?EIO=3&transport=polling&t=NU6-4O_ net::ERR_CONNECTION_REFUSED

**Comment by derogab** [comment]
Thanks for the tip. Updates are coming soon ...

**Comment by derogab** [comment]
This problem should have been fixed in the #47 pull request.
The `latest` version available and all versions above or equal to [v1.1.5](https://github.com/derogab/coingraph/releases/tag/v1.1.5) should work correctly.

Let me know!
