### ISSUE TITLE
Remove MySQL to use public APIs

### ISSUE THREAD

**Issue by derogab** [derogab/coingraph#9]
A developer on [hacker-news](https://news.ycombinator.com/item?id=15156021) made me notice that coingraph uses too many dependencies that can be replaced with home-made alternatives.

I have already replaced Apache with a webserver with the help of @gmemstr.

Another of these is the MySQL server.
I had in mind replacing the database using only Public APIs.

**Comment by Johnb21** [comment]
@derogab - Is this still something you need help with? Please let me know!

**Comment by derogab** [comment]
@Johnb21 Yes, sure.
